name: SWPacker Windows
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  VERSION_NAME: 1.1

jobs:
  Build_exec:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Config executables
        run: |
          mkdir build && cd build
          cmake -B ${{github.workspace}}\build -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ..

      - name: Build executables
        run: |
          cd ${{github.workspace}}\build
          cmake --build ${{github.workspace}}\build --config ${{env.BUILD_TYPE}}

      - name: Archive Executable
        uses: actions/upload-artifact@v3
        with:
          name: SWPacker
          path: ${{github.workspace}}\out\${{env.VERSION_NAME}}\Release\

  Build_Unpack_Shared:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Config executables
        run: |
          mkdir build && cd build
          cmake -B ${{github.workspace}}\build -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_UNPACK_LIB_SHARED=ON ..

      - name: Build executables
        run: |
          cd ${{github.workspace}}\build
          cmake --build ${{github.workspace}}\build --target SWEngine-unpacker_${{env.VERSION_NAME}} --config ${{env.BUILD_TYPE}}

      - name: Archive Library
        uses: actions/upload-artifact@v3
        with:
          name: SWPacker
          path: ${{github.workspace}}\out\${{env.VERSION_NAME}}\Release\

  Build_Unpack_Static:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Config executables
        run: |
          mkdir build && cd build
          cmake -B ${{github.workspace}}\build -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_UNPACK_LIB_STATIC=ON ..

      - name: Build executables
        run: |
          cd ${{github.workspace}}\build
          cmake --build ${{github.workspace}}\build --target SWEngine-unpacker_${{env.VERSION_NAME}} --config ${{env.BUILD_TYPE}}

      - name: Archive library
        uses: actions/upload-artifact@v3
        with:
          name: SWPacker
          path: ${{github.workspace}}\out\${{env.VERSION_NAME}}\Release\